### ISSUE TITLE
Failed with Python 3.6 and H5Py v2.8.0

### ISSUE THREAD

**Issue by Naereen** [jni/h5cat#1]
Hi,
I just downloaded and tried your script on XUbuntu 18.04, with Python 3.6 and H5Py 2.8.0.
I got this error (on [this example file](https://github.com/SMPyBandits/SMPyBandits/blob/master/plots/paper/example.hdf5?raw=true)).
```bash
$ h5cat example.hdf5
>>> example.hdf5

    env_0
Traceback (most recent call last):
  File "h5cat.py", line 44, in <module>
    main()
  File "h5cat.py", line 35, in main
    if type(f[g]) == h5py.highlevel.Dataset:
AttributeError: module 'h5py' has no attribute 'highlevel'
```
Thanks in advance!

**Comment by jni** [comment]
@Naereen Hi! (Nice profile pic! =) Thanks for your interest in this! I haven't updated this in a long time so it's not too surprising that it doesn't work! I'll try to have a look but honestly, it looks like this cool new project from @takluyver will do the same thing h5cat did but way better, so I recommend you try it!

https://pypi.org/project/h5glance/#description

**Comment by takluyver** [comment]
Thanks. :-) One nice thing h5cat offers is looking at multiple files at once - I can't easily copy that for h5glance, because I'm using the second positional argument for a path inside the file.

**Comment by Naereen** [comment]
@jni thanks for your very quick reply! No problem, don't worry.
Maybe you can specify in this project that it is not updated anymore, and point to @takluyver's tool?

@takluyver great job, h5glance is awesome :sparkles: !

**Comment by jni** [comment]
@Naereen I'm far too OCD to leave it broken. =D It's fixed *and* has a setup.py *and* is uploaded to PyPI, so you can just `pip install h5cat`.

NOW I can mark the repo as unmaintained. =P

**Comment by Naereen** [comment]
Who @jni that's impressive!
- pip install worked for me :+1:
- the bug is fixed for me :+1:
- you're incredibly fast :+1: :sparkles: !
